In [6]:
import pandas as pd

In [7]:
pr=pd.read_csv('E:/datasets/Property_Price_Train.csv')

In [8]:
pr.head()

,Id,Building_Class,Zoning_Class,Lot_Extent,Lot_Size,Road_Type,Lane_Type,Property_Shape,Land_Outline,Utility_Type,...,Pool_Area,Pool_Quality,Fence_Quality,Miscellaneous_Feature,Miscellaneous_Value,Month_Sold,Year_Sold,Sale_Type,Sale_Condition,Sale_Price
0,1,60,RLD,65.0,8450,Paved,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RLD,80.0,9600,Paved,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RLD,68.0,11250,Paved,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RLD,60.0,9550,Paved,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RLD,84.0,14260,Paved,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [9]:
pr.columns

Index(['Id', 'Building_Class', 'Zoning_Class', 'Lot_Extent', 'Lot_Size',
       'Road_Type', 'Lane_Type', 'Property_Shape', 'Land_Outline',
       'Utility_Type', 'Lot_Configuration', 'Property_Slope', 'Neighborhood',
       'Condition1', 'Condition2', 'House_Type', 'House_Design',
       'Overall_Material', 'House_Condition', 'Construction_Year',
       'Remodel_Year', 'Roof_Design', 'Roof_Quality', 'Exterior1st',
       'Exterior2nd', 'Brick_Veneer_Type', 'Brick_Veneer_Area',
       'Exterior_Material', 'Exterior_Condition', 'Foundation_Type',
       'Basement_Height', 'Basement_Condition', 'Exposure_Level',
       'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF',
       'Total_Basement_Area', 'Heating_Type', 'Heating_Quality',
       'Air_Conditioning', 'Electrical_System', 'First_Floor_Area',
       'Second_Floor_Area', 'LowQualFinSF', 'Grade_Living_Area',
       'Underground_Full_Bathroom', 'Underground_Half_Bathroom',
       'Full_Bathroom_Above_Grade', 'Half_Bathroom_Above_Grade',
       'Bedroom_Above_Grade', 'Kitchen_Above_Grade', 'Kitchen_Quality',
       'Rooms_Above_Grade', 'Functional_Rate', 'Fireplaces',
       'Fireplace_Quality', 'Garage', 'Garage_Built_Year',
       'Garage_Finish_Year', 'Garage_Size', 'Garage_Area', 'Garage_Quality',
       'Garage_Condition', 'Pavedd_Drive', 'W_Deck_Area', 'Open_Lobby_Area',
       'Enclosed_Lobby_Area', 'Three_Season_Lobby_Area', 'Screen_Lobby_Area',
       'Pool_Area', 'Pool_Quality', 'Fence_Quality', 'Miscellaneous_Feature',
       'Miscellaneous_Value', 'Month_Sold', 'Year_Sold', 'Sale_Type',
       'Sale_Condition', 'Sale_Price'],
      dtype='object')

In [10]:
pr.columns[pr.isnull().sum()*100/pr.shape[0]>50]

Index(['Lane_Type', 'Pool_Quality', 'Fence_Quality', 'Miscellaneous_Feature'], dtype='object')

In [11]:
pr=pr.loc[:,['Building_Class', 'Zoning_Class', 'Lot_Extent', 'Lot_Size',
       'Road_Type', 'Property_Shape', 'Land_Outline',
       'Utility_Type', 'Lot_Configuration', 'Property_Slope', 'Neighborhood',
       'Condition1', 'Condition2', 'House_Type', 'House_Design',
       'Overall_Material', 'House_Condition', 'Construction_Year',
       'Remodel_Year', 'Roof_Design', 'Roof_Quality', 'Exterior1st',
       'Exterior2nd', 'Brick_Veneer_Type', 'Brick_Veneer_Area',
       'Exterior_Material', 'Exterior_Condition', 'Foundation_Type',
       'Basement_Height', 'Basement_Condition', 'Exposure_Level',
       'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF',
       'Total_Basement_Area', 'Heating_Type', 'Heating_Quality',
       'Air_Conditioning', 'Electrical_System', 'First_Floor_Area',
       'Second_Floor_Area', 'LowQualFinSF', 'Grade_Living_Area',
       'Underground_Full_Bathroom', 'Underground_Half_Bathroom',
       'Full_Bathroom_Above_Grade', 'Half_Bathroom_Above_Grade',
       'Bedroom_Above_Grade', 'Kitchen_Above_Grade', 'Kitchen_Quality',
       'Rooms_Above_Grade', 'Functional_Rate', 'Fireplaces',
       'Fireplace_Quality', 'Garage', 'Garage_Built_Year',
       'Garage_Finish_Year', 'Garage_Size', 'Garage_Area', 'Garage_Quality',
       'Garage_Condition', 'Pavedd_Drive', 'W_Deck_Area', 'Open_Lobby_Area',
       'Enclosed_Lobby_Area', 'Three_Season_Lobby_Area', 'Screen_Lobby_Area',
       'Pool_Area',
       'Miscellaneous_Value', 'Month_Sold', 'Year_Sold', 'Sale_Type',
       'Sale_Condition', 'Sale_Price']]

In [12]:
pr.head()

,Building_Class,Zoning_Class,Lot_Extent,Lot_Size,Road_Type,Property_Shape,Land_Outline,Utility_Type,Lot_Configuration,Property_Slope,...,Enclosed_Lobby_Area,Three_Season_Lobby_Area,Screen_Lobby_Area,Pool_Area,Miscellaneous_Value,Month_Sold,Year_Sold,Sale_Type,Sale_Condition,Sale_Price
0,60,RLD,65.0,8450,Paved,Reg,Lvl,AllPub,I,GS,...,20.337934,0,0,0,0,2,2008,WD,Normal,208500
1,20,RLD,80.0,9600,Paved,Reg,Lvl,AllPub,FR2P,GS,...,15.039392,0,0,0,0,5,2007,WD,Normal,181500
2,60,RLD,68.0,11250,Paved,IR1,Lvl,AllPub,I,GS,...,-46.232198,0,0,0,0,9,2008,WD,Normal,223500
3,70,RLD,60.0,9550,Paved,IR1,Lvl,AllPub,C,GS,...,60.921821,0,0,0,0,2,2006,WD,Abnorml,140000
4,60,RLD,84.0,14260,Paved,IR1,Lvl,AllPub,FR2P,GS,...,21.788818,0,0,0,0,12,2008,WD,Normal,250000

In [13]:
pr.isnull().sum()

Building_Class      0
Zoning_Class        0
Lot_Extent        259
Lot_Size            0
Road_Type           0
                 ...
Month_Sold          0
Year_Sold           0
Sale_Type           0
Sale_Condition      0
Sale_Price          0
Length: 76, dtype: int64

In [14]:
pr.describe(include='all')

,Building_Class,Zoning_Class,Lot_Extent,Lot_Size,Road_Type,Property_Shape,Land_Outline,Utility_Type,Lot_Configuration,Property_Slope,...,Enclosed_Lobby_Area,Three_Season_Lobby_Area,Screen_Lobby_Area,Pool_Area,Miscellaneous_Value,Month_Sold,Year_Sold,Sale_Type,Sale_Condition,Sale_Price
count,1459.000000,1459,1200.000000,1459.000000,1459,1459,1459,1459,1459,1459,...,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459,1459,1459.000000
unique,NaN,5,NaN,NaN,2,4,4,2,5,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,6,NaN
top,NaN,RLD,NaN,NaN,Paved,Reg,Lvl,AllPub,I,GS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WD,Normal,NaN
freq,NaN,1150,NaN,NaN,1453,924,1310,1458,1051,1381,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1266,1197,NaN
mean,56.922550,NaN,70.045833,10517.225497,NaN,NaN,NaN,NaN,NaN,NaN,...,24.580227,3.411926,15.071282,2.760795,43.518849,6.322138,2007.815627,NaN,NaN,180944.102810
std,42.304033,NaN,24.294456,9984.675721,NaN,NaN,NaN,NaN,NaN,NaN,...,61.353507,29.327247,55.775138,40.191018,496.291826,2.704540,1.328542,NaN,NaN,79464.918335
min,20.000000,NaN,21.000000,1300.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,-164.807386,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,NaN,NaN,34900.000000
25%,20.000000,NaN,59.000000,7549.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,-16.807302,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,NaN,NaN,129950.000000
50%,50.000000,NaN,69.000000,9477.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,25.026953,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,NaN,NaN,163000.000000
75%,70.000000,NaN,80.000000,11603.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,66.237591,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,NaN,NaN,214000.000000
max,190.000000,NaN,313.000000,215245.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,225.762714,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,NaN,NaN,755000.000000

In [30]:

pr.Lot_Extent=pr.Lot_Extent.fillna(pr.Lot_Extent.median())
pr.Brick_Veneer_Type=pr.Brick_Veneer_Type.fillna('None')
pr.Exposure_Level=pr.Exposure_Level.fillna('No')
pr.BsmtFinType1=pr.BsmtFinType1.fillna('Unf')
pr.BsmtFinType2=pr.BsmtFinType2.fillna('Unf')
pr.Electrical_System=pr.Electrical_System.fillna('SBrkr')
pr.Garage_Built_Year=pr.Garage_Built_Year.fillna('2005')
pr.Fireplace_Quality=pr.Fireplace_Quality.fillna('Gd')
pr.Garage=pr.Garage.fillna('Attchd')
pr.Garage_Finish_Year=pr.Garage_Finish_Year.fillna('Unf')
pr.Garage_Quality=pr.Garage_Quality.fillna('TA')
pr.Garage_Condition=pr.Garage_Condition.fillna('TA')
pr.Basement_Height=pr.Basement_Height.fillna('TA')
pr.Basement_Condition=pr.Basement_Condition.fillna('TA')
pr.Brick_Veneer_Area=pr.Brick_Veneer_Area.fillna(pr.Brick_Veneer_Area.mean())


pr.isnull().sum()

Building_Class               0
Zoning_Class                 0
Lot_Extent                   0
Lot_Size                     0
Road_Type                    0
Property_Shape               0
Land_Outline                 0
Utility_Type                 0
Lot_Configuration            0
Property_Slope               0
Neighborhood                 0
Condition1                   0
Condition2                   0
House_Type                   0
House_Design                 0
Overall_Material             0
House_Condition              0
Construction_Year            0
Remodel_Year                 0
Roof_Design                  0
Roof_Quality                 0
Exterior1st                  0
Exterior2nd                  0
Brick_Veneer_Type            0
Brick_Veneer_Area            0
Exterior_Material            0
Exterior_Condition           0
Foundation_Type              0
Basement_Height              0
Basement_Condition           0
Exposure_Level               0
BsmtFinType1                 0
BsmtFinSF1                   0
BsmtFinType2                 0
BsmtFinSF2                   0
BsmtUnfSF                    0
Total_Basement_Area          0
Heating_Type                 0
Heating_Quality              0
Air_Conditioning             0
Electrical_System            0
First_Floor_Area             0
Second_Floor_Area            0
LowQualFinSF                 0
Grade_Living_Area            0
Underground_Full_Bathroom    0
Underground_Half_Bathroom    0
Full_Bathroom_Above_Grade    0
Half_Bathroom_Above_Grade    0
Bedroom_Above_Grade          0
Kitchen_Above_Grade          0
Kitchen_Quality              0
Rooms_Above_Grade            0
Functional_Rate              0
Fireplaces                   0
Fireplace_Quality            0
Garage                       0
Garage_Built_Year            0
Garage_Finish_Year           0
Garage_Size                  0
Garage_Area                  0
Garage_Quality               0
Garage_Condition             0
Pavedd_Drive                 0
W_Deck_Area                  0
Open_Lobby_Area              0
Enclosed_Lobby_Area          0
Three_Season_Lobby_Area      0
Screen_Lobby_Area            0
Pool_Area                    0
Miscellaneous_Value          0
Month_Sold                   0
Year_Sold                    0
Sale_Type                    0
Sale_Condition               0
Sale_Price                   0
dtype: int64

In [16]:
pr.describe(include='all')

,Building_Class,Zoning_Class,Lot_Extent,Lot_Size,Road_Type,Property_Shape,Land_Outline,Utility_Type,Lot_Configuration,Property_Slope,...,Enclosed_Lobby_Area,Three_Season_Lobby_Area,Screen_Lobby_Area,Pool_Area,Miscellaneous_Value,Month_Sold,Year_Sold,Sale_Type,Sale_Condition,Sale_Price
count,1459.000000,1459,1459.000000,1459.000000,1459,1459,1459,1459,1459,1459,...,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459,1459,1459.000000
unique,NaN,5,NaN,NaN,2,4,4,2,5,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,6,NaN
top,NaN,RLD,NaN,NaN,Paved,Reg,Lvl,AllPub,I,GS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WD,Normal,NaN
freq,NaN,1150,NaN,NaN,1453,924,1310,1458,1051,1381,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1266,1197,NaN
mean,56.922550,NaN,69.860178,10517.225497,NaN,NaN,NaN,NaN,NaN,NaN,...,24.580227,3.411926,15.071282,2.760795,43.518849,6.322138,2007.815627,NaN,NaN,180944.102810
std,42.304033,NaN,22.034819,9984.675721,NaN,NaN,NaN,NaN,NaN,NaN,...,61.353507,29.327247,55.775138,40.191018,496.291826,2.704540,1.328542,NaN,NaN,79464.918335
min,20.000000,NaN,21.000000,1300.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,-164.807386,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,NaN,NaN,34900.000000
25%,20.000000,NaN,60.000000,7549.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,-16.807302,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,NaN,NaN,129950.000000
50%,50.000000,NaN,69.000000,9477.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,25.026953,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,NaN,NaN,163000.000000
75%,70.000000,NaN,79.000000,11603.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,66.237591,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,NaN,NaN,214000.000000
max,190.000000,NaN,313.000000,215245.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,225.762714,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,NaN,NaN,755000.000000

In [31]:
import sklearn
from sklearn.preprocessing import LabelEncoder

In [32]:
le=LabelEncoder()

In [33]:
pr.select_dtypes(include='object').columns

Index(['Zoning_Class', 'Road_Type', 'Property_Shape', 'Land_Outline',
       'Utility_Type', 'Lot_Configuration', 'Property_Slope', 'Neighborhood',
       'Condition1', 'Condition2', 'House_Type', 'House_Design', 'Roof_Design',
       'Roof_Quality', 'Exterior1st', 'Exterior2nd', 'Brick_Veneer_Type',
       'Exterior_Material', 'Exterior_Condition', 'Foundation_Type',
       'Basement_Height', 'Basement_Condition', 'Exposure_Level',
       'BsmtFinType1', 'BsmtFinType2', 'Heating_Type', 'Heating_Quality',
       'Air_Conditioning', 'Electrical_System', 'Kitchen_Quality',
       'Functional_Rate', 'Fireplace_Quality', 'Garage', 'Garage_Built_Year',
       'Garage_Finish_Year', 'Garage_Quality', 'Garage_Condition',
       'Pavedd_Drive', 'Sale_Type', 'Sale_Condition'],
      dtype='object')

In [34]:
pd.set_option( "display.max_rows" , None)
pr.info()
pr.Brick_Veneer_Area.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 76 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Building_Class             1459 non-null   int64
 1   Zoning_Class               1459 non-null   object
 2   Lot_Extent                 1459 non-null   float64
 3   Lot_Size                   1459 non-null   int64
 4   Road_Type                  1459 non-null   object
 5   Property_Shape             1459 non-null   object
 6   Land_Outline               1459 non-null   object
 7   Utility_Type               1459 non-null   object
 8   Lot_Configuration          1459 non-null   object
 9   Property_Slope             1459 non-null   object
 10  Neighborhood               1459 non-null   object
 11  Condition1                 1459 non-null   object
 12  Condition2                 1459 non-null   object
 13  House_Type                 1459 non-null   object
 14  House_Design               1459 non-null   object
 15  Overall_Material           1459 non-null   int64
 16  House_Condition            1459 non-null   int64
 17  Construction_Year          1459 non-null   int64
 18  Remodel_Year               1459 non-null   int64
 19  Roof_Design                1459 non-null   object
 20  Roof_Quality               1459 non-null   object
 21  Exterior1st                1459 non-null   object
 22  Exterior2nd                1459 non-null   object
 23  Brick_Veneer_Type          1459 non-null   object
 24  Brick_Veneer_Area          1459 non-null   float64
 25  Exterior_Material          1459 non-null   object
 26  Exterior_Condition         1459 non-null   object
 27  Foundation_Type            1459 non-null   object
 28  Basement_Height            1459 non-null   object
 29  Basement_Condition         1459 non-null   object
 30  Exposure_Level             1459 non-null   object
 31  BsmtFinType1               1459 non-null   object
 32  BsmtFinSF1                 1459 non-null   int64
 33  BsmtFinType2               1459 non-null   object
 34  BsmtFinSF2                 1459 non-null   int64
 35  BsmtUnfSF                  1459 non-null   int64
 36  Total_Basement_Area        1459 non-null   int64
 37  Heating_Type               1459 non-null   object
 38  Heating_Quality            1459 non-null   object
 39  Air_Conditioning           1459 non-null   object
 40  Electrical_System          1459 non-null   object
 41  First_Floor_Area           1459 non-null   int64
 42  Second_Floor_Area          1459 non-null   int64
 43  LowQualFinSF               1459 non-null   int64
 44  Grade_Living_Area          1459 non-null   int64
 45  Underground_Full_Bathroom  1459 non-null   int64
 46  Underground_Half_Bathroom  1459 non-null   int64
 47  Full_Bathroom_Above_Grade  1459 non-null   int64
 48  Half_Bathroom_Above_Grade  1459 non-null   int64
 49  Bedroom_Above_Grade        1459 non-null   int64
 50  Kitchen_Above_Grade        1459 non-null   int64
 51  Kitchen_Quality            1459 non-null   object
 52  Rooms_Above_Grade          1459 non-null   int64
 53  Functional_Rate            1459 non-null   object
 54  Fireplaces                 1459 non-null   int64
 55  Fireplace_Quality          1459 non-null   object
 56  Garage                     1459 non-null   object
 57  Garage_Built_Year          1459 non-null   object
 58  Garage_Finish_Year         1459 non-null   object
 59  Garage_Size                1459 non-null   int64
 60  Garage_Area                1459 non-null   float64
 61  Garage_Quality             1459 non-null   object
 62  Garage_Condition           1459 non-null   object
 63  Pavedd_Drive               1459 non-null   object
 64  W_Deck_Area                1459 non-null   float64
 65  Open_Lobby_Area            1459 non-null   float64
 66  Enclosed_Lobby_Area        1459 non-null   float64
 67  Three_Season_Lobby_Area    1459 non-null   int64
 68  Screen_Lobby_Area          1459 non-null   int64
 69  Pool_Area                  1459 non-null   int64
 70  Miscellaneous_Value        1459 non-null   int64
 71  Month_Sold                 1459 non-null   int64
 72  Year_Sold                  1459 non-null   int64
 73  Sale_Type                  1459 non-null   object
 74  Sale_Condition             1459 non-null   object
 75  Sale_Price                 1459 non-null   int64
dtypes: float64(6), int64(30), object(40)
memory usage: 866.4+ KB

count    1459.00000
mean      103.75672
std       180.61060
min         0.00000
25%         0.00000
50%         0.00000
75%       164.50000
max      1600.00000
Name: Brick_Veneer_Area, dtype: float64

In [35]:
pr.isnull().sum()

Building_Class               0
Zoning_Class                 0
Lot_Extent                   0
Lot_Size                     0
Road_Type                    0
Property_Shape               0
Land_Outline                 0
Utility_Type                 0
Lot_Configuration            0
Property_Slope               0
Neighborhood                 0
Condition1                   0
Condition2                   0
House_Type                   0
House_Design                 0
Overall_Material             0
House_Condition              0
Construction_Year            0
Remodel_Year                 0
Roof_Design                  0
Roof_Quality                 0
Exterior1st                  0
Exterior2nd                  0
Brick_Veneer_Type            0
Brick_Veneer_Area            0
Exterior_Material            0
Exterior_Condition           0
Foundation_Type              0
Basement_Height              0
Basement_Condition           0
Exposure_Level               0
BsmtFinType1                 0
BsmtFinSF1                   0
BsmtFinType2                 0
BsmtFinSF2                   0
BsmtUnfSF                    0
Total_Basement_Area          0
Heating_Type                 0
Heating_Quality              0
Air_Conditioning             0
Electrical_System            0
First_Floor_Area             0
Second_Floor_Area            0
LowQualFinSF                 0
Grade_Living_Area            0
Underground_Full_Bathroom    0
Underground_Half_Bathroom    0
Full_Bathroom_Above_Grade    0
Half_Bathroom_Above_Grade    0
Bedroom_Above_Grade          0
Kitchen_Above_Grade          0
Kitchen_Quality              0
Rooms_Above_Grade            0
Functional_Rate              0
Fireplaces                   0
Fireplace_Quality            0
Garage                       0
Garage_Built_Year            0
Garage_Finish_Year           0
Garage_Size                  0
Garage_Area                  0
Garage_Quality               0
Garage_Condition             0
Pavedd_Drive                 0
W_Deck_Area                  0
Open_Lobby_Area              0
Enclosed_Lobby_Area          0
Three_Season_Lobby_Area      0
Screen_Lobby_Area            0
Pool_Area                    0
Miscellaneous_Value          0
Month_Sold                   0
Year_Sold                    0
Sale_Type                    0
Sale_Condition               0
Sale_Price                   0
dtype: int64

In [39]:
pr[pr.select_dtypes(include=['object']).columns]=pr[pr.select_dtypes(include=['object']).columns].apply(le.fit_transform)

TypeError: fit_transform() missing 1 required positional argument: 'y'

In [37]:
pr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 76 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Building_Class             1459 non-null   int64
 1   Zoning_Class               1459 non-null   object
 2   Lot_Extent                 1459 non-null   float64
 3   Lot_Size                   1459 non-null   int64
 4   Road_Type                  1459 non-null   object
 5   Property_Shape             1459 non-null   object
 6   Land_Outline               1459 non-null   object
 7   Utility_Type               1459 non-null   object
 8   Lot_Configuration          1459 non-null   object
 9   Property_Slope             1459 non-null   object
 10  Neighborhood               1459 non-null   object
 11  Condition1                 1459 non-null   object
 12  Condition2                 1459 non-null   object
 13  House_Type                 1459 non-null   object
 14  House_Design               1459 non-null   object
 15  Overall_Material           1459 non-null   int64
 16  House_Condition            1459 non-null   int64
 17  Construction_Year          1459 non-null   int64
 18  Remodel_Year               1459 non-null   int64
 19  Roof_Design                1459 non-null   object
 20  Roof_Quality               1459 non-null   object
 21  Exterior1st                1459 non-null   object
 22  Exterior2nd                1459 non-null   object
 23  Brick_Veneer_Type          1459 non-null   object
 24  Brick_Veneer_Area          1459 non-null   float64
 25  Exterior_Material          1459 non-null   object
 26  Exterior_Condition         1459 non-null   object
 27  Foundation_Type            1459 non-null   object
 28  Basement_Height            1459 non-null   object
 29  Basement_Condition         1459 non-null   object
 30  Exposure_Level             1459 non-null   object
 31  BsmtFinType1               1459 non-null   object
 32  BsmtFinSF1                 1459 non-null   int64
 33  BsmtFinType2               1459 non-null   object
 34  BsmtFinSF2                 1459 non-null   int64
 35  BsmtUnfSF                  1459 non-null   int64
 36  Total_Basement_Area        1459 non-null   int64
 37  Heating_Type               1459 non-null   object
 38  Heating_Quality            1459 non-null   object
 39  Air_Conditioning           1459 non-null   object
 40  Electrical_System          1459 non-null   object
 41  First_Floor_Area           1459 non-null   int64
 42  Second_Floor_Area          1459 non-null   int64
 43  LowQualFinSF               1459 non-null   int64
 44  Grade_Living_Area          1459 non-null   int64
 45  Underground_Full_Bathroom  1459 non-null   int64
 46  Underground_Half_Bathroom  1459 non-null   int64
 47  Full_Bathroom_Above_Grade  1459 non-null   int64
 48  Half_Bathroom_Above_Grade  1459 non-null   int64
 49  Bedroom_Above_Grade        1459 non-null   int64
 50  Kitchen_Above_Grade        1459 non-null   int64
 51  Kitchen_Quality            1459 non-null   object
 52  Rooms_Above_Grade          1459 non-null   int64
 53  Functional_Rate            1459 non-null   object
 54  Fireplaces                 1459 non-null   int64
 55  Fireplace_Quality          1459 non-null   object
 56  Garage                     1459 non-null   object
 57  Garage_Built_Year          1459 non-null   object
 58  Garage_Finish_Year         1459 non-null   object
 59  Garage_Size                1459 non-null   int64
 60  Garage_Area                1459 non-null   float64
 61  Garage_Quality             1459 non-null   object
 62  Garage_Condition           1459 non-null   object
 63  Pavedd_Drive               1459 non-null   object
 64  W_Deck_Area                1459 non-null   float64
 65  Open_Lobby_Area            1459 non-null   float64
 66  Enclosed_Lobby_Area        1459 non-null   float64
 67  Three_Season_Lobby_Area    1459 non-null   int64
 68  Screen_Lobby_Area          1459 non-null   int64
 69  Pool_Area                  1459 non-null   int64
 70  Miscellaneous_Value        1459 non-null   int64
 71  Month_Sold                 1459 non-null   int64
 72  Year_Sold                  1459 non-null   int64
 73  Sale_Type                  1459 non-null   object
 74  Sale_Condition             1459 non-null   object
 75  Sale_Price                 1459 non-null   int64
dtypes: float64(6), int64(30), object(40)
memory usage: 866.4+ KB

In [ ]:
#pr.Zoning_Class=le.fit_transform(pr.Zoning_Class)

pr.Road_Type=le.fit_transform(pr.Road_Type)
pr.Property_Shape=le.fit_transform(pr.Property_Shape)
pr.Land_Outline=le.fit_transform(pr.Land_Outline)
pr.Utility_Type=le.fit_transform(pr.Utility_Type)
pr.Lot_Configuration=le.fit_transform(pr.Lot_Configuration)
pr.Property_Slope=le.fit_transform(pr.Property_Slope)
pr.Neighborhood=le.fit_transform(pr.Neighborhood)
pr.Condition1=le.fit_transform(pr.Condition1)
pr.Condition2=le.fit_transform(pr.Condition2)
pr.House_Type=le.fit_transform(pr.House_Type)
pr.House_Design=le.fit_transform(pr.House_Design)

pr.Roof_Design=le.fit_transform(pr.Roof_Design)
pr.Roof_Quality=le.fit_transform(pr.Roof_Quality)
pr.Exterior1st=le.fit_transform(pr.Exterior1st)
pr.Exterior2nd=le.fit_transform(pr.Exterior2nd)
pr.Brick_Veneer_Type=le.fit_transform(pr.Brick_Veneer_Type)
pr.Exterior_Material=le.fit_transform(pr.Exterior_Material)
pr.Exterior_Condition=le.fit_transform(pr.Exterior_Condition)
pr.Foundation_Type=le.fit_transform(pr.Foundation_Type)
pr.Basement_Height=le.fit_transform(pr.Basement_Height)
pr.Basement_Condition=le.fit_transform(pr.Basement_Condition)
pr.Exposure_Level=le.fit_transform(pr.Exposure_Level)
pr.BsmtFinType1=le.fit_transform(pr.BsmtFinType1)
pr.BsmtFinType2=le.fit_transform(pr.BsmtFinType2)

pr.Heating_Type=le.fit_transform(pr.Heating_Type)
pr.Heating_Quality=le.fit_transform(pr.Heating_Quality)
pr.Air_Conditioning=le.fit_transform(pr.Air_Conditioning)
pr.Electrical_System=le.fit_transform(pr.Electrical_System)
pr.Kitchen_Quality=le.fit_transform(pr.Kitchen_Quality)
pr.Functional_Rate=le.fit_transform(pr.Functional_Rate)
pr.Fireplace_Quality=le.fit_transform(pr.Fireplace_Quality)
pr.Garage=le.fit_transform(pr.Garage)
pr.Garage_Built_Year=le.fit_transform(pr.Garage_Built_Year)
pr.Garage_Finish_Year=le.fit_transform(pr.Garage_Finish_Year)
pr.Garage_Quality=le.fit_transform(pr.Garage_Quality)
pr.Garage_Condition=le.fit_transform(pr.Garage_Condition)
pr.Pavedd_Drive=le.fit_transform(pr.Pavedd_Drive)
pr.Sale_Type=le.fit_transform(pr.Sale_Type)
pr.Sale_Condition=le.fit_transform(pr.Sale_Condition)